// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAog4z3VEbWeyZ8mtNAS8voo4i5MpGx_-A',
    appId: '1:515184074822:android:3e6173b006b7591eab6a47',
    messagingSenderId: '515184074822',
    projectId: 'video-audio-chat-36ab0',
    storageBucket: 'video-audio-chat-36ab0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjPcfiWXj-9YV37KRUL4qty0f5CvzKW5s',
    appId: '1:515184074822:ios:36af9cfca691e5bfab6a47',
    messagingSenderId: '515184074822',
    projectId: 'video-audio-chat-36ab0',
    storageBucket: 'video-audio-chat-36ab0.appspot.com',
    androidClientId: '515184074822-df3gp9tjdc7gndh8229pbslpm7kb34lj.apps.googleusercontent.com',
    iosClientId: '515184074822-9ftrdha56u8gjpldlap43gtrip6qciak.apps.googleusercontent.com',
    iosBundleId: 'com.dbestech.chatty',
  );
}
